// `harness init` - generate .harnessrc, print bootstrap prompt.

import path from 'node:path';
import { writeFile, exists } from '../lib/fsx.mjs';
import { harnessrcPath } from '../lib/paths.mjs';
import { resolveStack } from '../lib/detector.mjs';

export async function init(args, opts) {
  const [stackArg] = args;
  const stack = await resolveStack(stackArg);
  const targetRoot = process.cwd();

  if (await exists(harnessrcPath(targetRoot))) {
    if (!opts.json) {
      process.stderr.write(`.harnessrc already exists. Re-run with --force to overwrite.\n`);
    }
    return 1;
  }

  const rc = [
    '# Harness configuration for this project.',
    '# Generated by "harness init". See meta-harness README for details.',
    `stack: ${stack.id}`,
    'harness_version: 0.1.1',
    '',
  ].join('\n');
  await writeFile(harnessrcPath(targetRoot), rc);

  return { stack: stack.id, message: 'initialized' };
}
