import { describe, expect, it } from 'vitest';
import { buildMediaIngestionPlan, buildProcessingTargetKey } from './media-ingestion';

// Minimal valid 1x1 pixel grayscale PNG (generated by sharp)
const validPngBuffer = Buffer.from([
  0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, // PNG signature
  0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52, // IHDR length + type
  0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, // 1x1 dimensions
  0x08, 0x02, 0x00, 0x00, 0x00, 0x90, 0x77, 0x53, // bit depth, color type, CRC
  0xDE, 0x00, 0x00, 0x00, 0x0C, 0x49, 0x44, 0x41, // IDAT length + type
  0x54, 0x08, 0xD7, 0x63, 0xD8, 0xAE, 0xB8, 0x82, // compressed data
  0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44, // IEND
  0xAE, 0x42, 0x60, 0x82, // IEND CRC
]);
const validMp4Buffer = Buffer.from([0x00, 0x00, 0x00, 0x18, 0x66, 0x74, 0x79, 0x70, 0x69, 0x73, 0x6f, 0x6d]);

describe('media ingestion planning', () => {
  it('computes checksum, deterministic object key, and image thumbnail job', async () => {
    const plan = await buildMediaIngestionPlan({
      projectId: 'proj_1',
      originalName: 'north-gate.png',
      mimeType: 'image/png',
      sizeBytes: validPngBuffer.length,
      buffer: validPngBuffer,
    });

    expect(plan.checksum).toBeDefined();
    expect(plan.storageKey).toContain('projects/proj_1/originals/');
    expect(plan.storageKey).toContain('.png');
    expect(plan.processingJobType).toBe('THUMBNAIL');
    expect(plan.mediaType).toBe('IMAGE');
  });

  it('plans frame extraction for videos', async () => {
    const plan = await buildMediaIngestionPlan({
      projectId: 'proj_1',
      originalName: 'clip.mp4',
      mimeType: 'video/mp4',
      sizeBytes: validMp4Buffer.length,
      buffer: validMp4Buffer,
    });

    expect(plan.mediaType).toBe('VIDEO');
    expect(plan.processingJobType).toBe('EXTRACT_FRAMES');
    expect(buildProcessingTargetKey('proj_1', 'asset_1', plan.processingJobType)).toBe(
      'projects/proj_1/derivatives/asset_1/frames.json'
    );
  });
});
